apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: chat-bot-rhoai-test 
  janus-idp.io/tekton: chat-bot-rhoai-test
  backstage.io/kubernetes-id: chat-bot-rhoai-test
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: chat-bot-rhoai-test
resources: 
- application-dev.yaml